function net = addClassifier(net, clsShape)
    
    convOpts = {'CudnnWorkspaceLimit', 512*512*512} ;

    net.layers{end+1} = struct('type', 'conv', 'name', 'prediction', ...
                               'weights', {{0.01*randn(1, 1, clsShape(1), clsShape(2), 'single'), ...
                                ones(clsShape(2), 1, 'single')}}, ...
                               'stride', 1, ...
                               'pad', 0, ...
                               'dilate', 1, ...
                               'learningRate', [1 2], ...
                               'weightDecay', [1 0], ...
                               'opts', {convOpts}) ;

    net.layers{end+1} = struct('type', 'softmaxloss', 'name', 'loss') ;
end

