function net = addGPooling(net, poolShape, poolMethod)
    
    net.layers{end+1} = struct('type', 'pool', 'name', 'gpool', ...
                               'method', poolMethod, ...
                               'pool', poolShape, ...
                               'stride', 1, ...
                               'pad', 0) ;
end

